// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx9WtriFZtaS9ht37e3oSLKFbYGI03fyc',
    appId: '1:732861098111:web:041afdbe107318f96eb74a',
    messagingSenderId: '732861098111',
    projectId: 'finote-bd174',
    authDomain: 'finote-bd174.firebaseapp.com',
    storageBucket: 'finote-bd174.firebasestorage.app',
    measurementId: 'G-JK4LD2KT7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJMMDTkkKmmvLm8xAqyJay385m_5tOjA',
    appId: '1:732861098111:android:ce89eb0409fa0b966eb74a',
    messagingSenderId: '732861098111',
    projectId: 'finote-bd174',
    storageBucket: 'finote-bd174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT-dxUroOMGsKaJrzef-msUhiUKxuULE4',
    appId: '1:732861098111:ios:9c97633998e7b8196eb74a',
    messagingSenderId: '732861098111',
    projectId: 'finote-bd174',
    storageBucket: 'finote-bd174.firebasestorage.app',
    iosBundleId: 'com.example.finote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT-dxUroOMGsKaJrzef-msUhiUKxuULE4',
    appId: '1:732861098111:ios:9c97633998e7b8196eb74a',
    messagingSenderId: '732861098111',
    projectId: 'finote-bd174',
    storageBucket: 'finote-bd174.firebasestorage.app',
    iosBundleId: 'com.example.finote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx9WtriFZtaS9ht37e3oSLKFbYGI03fyc',
    appId: '1:732861098111:web:e3596e87e3309ed56eb74a',
    messagingSenderId: '732861098111',
    projectId: 'finote-bd174',
    authDomain: 'finote-bd174.firebaseapp.com',
    storageBucket: 'finote-bd174.firebasestorage.app',
    measurementId: 'G-S6RW2C4B6C',
  );
}
