// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsOb7wCftsVuyvxKxuUKNrG14WjVOSCI',
    appId: '1:243787968515:web:5b4b1d36325dae77b55e36',
    messagingSenderId: '243787968515',
    projectId: 'phone-verification-6c232',
    authDomain: 'phone-verification-6c232.firebaseapp.com',
    storageBucket: 'phone-verification-6c232.firebasestorage.app',
    measurementId: 'G-Q61N9BBQPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG73CRkpUtiP07WcXDsDXjwPmlatYsGes',
    appId: '1:243787968515:android:33743a14e070d154b55e36',
    messagingSenderId: '243787968515',
    projectId: 'phone-verification-6c232',
    storageBucket: 'phone-verification-6c232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtkWl5gsc3vwIqNwGrdc35Nc4rcqLJNp0',
    appId: '1:243787968515:ios:f8740f88dec241cbb55e36',
    messagingSenderId: '243787968515',
    projectId: 'phone-verification-6c232',
    storageBucket: 'phone-verification-6c232.firebasestorage.app',
    iosBundleId: 'com.example.promptPolisherAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtkWl5gsc3vwIqNwGrdc35Nc4rcqLJNp0',
    appId: '1:243787968515:ios:f8740f88dec241cbb55e36',
    messagingSenderId: '243787968515',
    projectId: 'phone-verification-6c232',
    storageBucket: 'phone-verification-6c232.firebasestorage.app',
    iosBundleId: 'com.example.promptPolisherAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrsOb7wCftsVuyvxKxuUKNrG14WjVOSCI',
    appId: '1:243787968515:web:3cc4561846165e67b55e36',
    messagingSenderId: '243787968515',
    projectId: 'phone-verification-6c232',
    authDomain: 'phone-verification-6c232.firebaseapp.com',
    storageBucket: 'phone-verification-6c232.firebasestorage.app',
    measurementId: 'G-F8PWBZ2PCH',
  );
}
